apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-deployment
  labels:
    app: redis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-api
  template:
    metadata:
      labels:
        app: redis-api
    spec:
      containers:
        - name: redis-api
          image: java_rest_api_to_redis:kubernetes
          imagePullPolicy: Never
          ports:
            - containerPort: 8080