apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api-deployment
  labels:
    app: redis-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-api
  template:
    metadata:
      labels:
        app: redis-api
    spec:
      containers:
        - name: redis-api
            image: sandeepkumarguptap/redis_api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080